# file: noinspection undefined
server:
  port: 8889

jwt:
  secret:
    key: c2VjdXJlc2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /swagger-doc/v3/api-docs
  swagger-ui:
    path: /swagger-doc/swagger-ui.html

spring:
  r2dbc:
    url: r2dbc:mysql://root:root@localhost:3306/klear_financial
    pool:
      enabled: true
      initial-size: 5
      max-size: 20

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: trade-order-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.value.default.type: com.klear.tradesettlement.model.TradeOrder
        spring.json.trusted.packages: '*'